# -*- coding: utf-8 -*-
"""LinkedInPostCreator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1joQOCItXkKMFXOy0pvCo4hCPzGbZsntz
"""

!pip install -q feedparser
!pip install -q google-generativeai

# ==========================================
# STEP 1: IMPORT THE REQUIRED TOOLS
# ==========================================

# Import the tool that reads news feeds (RSS feeds) from websites
import feedparser

# Import Google's AI tool to generate the text for the post
import google.generativeai as genai

#Import the tool that is used for the sleep function
import time

# Import Python's built-in email alert tools
import smtplib

from email.mime.text import MIMEText

from email.mime.multipart import MIMEMultipart

import urllib.parse

import requests

# ==========================================
# STEP 2: SET UP THE AI MODEL
# ==========================================

# Tell the AI tool what your secret password (API key) is so it lets you use it
genai.configure(api_key="XXXX")

# Choose which specific AI Model to use. 'gemini-2.5-flash' is fast and free.
model = genai.GenerativeModel('gemini-2.5-flash')

# ===========================================
# STEP 3: FIND THE LATEST NEWS (RATE LIMITED)
# ===========================================


# Highly targeted RSS feeds for E-payments, ATMs, and Fintech infrastructure
news_links = [
    # --- The Core Payment & Infrastructure Feeds ---
    "https://www.paymentsdive.com/feeds/news/",    # Excellent deep dives into payment schemes and regulation
    "https://www.atmia.com/rss/",                  # ATM Industry Association (Highly specific to ATM software/hardware)
    "https://members.nfcw.com/feed/",              # NFC World (Dedicated to Contactless, POS, and digital wallets)

    # --- The Global Fintech Heavyweights ---
    "https://www.pymnts.com/feed/",                # Broad e-commerce and digital payments data
    "https://www.finextra.com/rss/headlines.aspx", # Bank-to-bank and global scheme updates
    "https://thepaypers.com/rss",                  # Great for B2B payments and transaction flow news
    "https://www.fintechfutures.com/feed/"         # Core banking technology updates
]

#This is an empty array (list), that will be later on filled with the articles found.
found_articles = []

# A for Loop to iterate through each web link in our list one by one.
for link in news_links:

    print(f"Fetching news from: {link}")

    # Read the webpage at this link
    feed = feedparser.parse(link)

    # Look at just the first 2 articles in this specific feed
    for article in feed.entries[:2]:
        found_articles.append({
            "Title": article.title,

            #Here I just requested a certian type of tag that could be present in some websites and could not be there.
            #So I did a get request, if there is a tag by this name, return it, else return an empty output so the code would not crash
            "Summary": article.get("summary", ""),
            "Link": article.link
        })

    # Tell the script to completely freeze for 3 seconds before checking the next link.
    # This could prevent the "Too Many Requests" error.
    time.sleep(3)

# Keep only one article
top_3_articles = found_articles[:1]
print("\nSuccessfully gathered articles needed!")

# ============================================
# STEP 4: USE THE AI MODEL TO WRITE THE POSTS
# ============================================

final_output = ""

# Loop through our top 3 articles one by one
for article in top_3_articles:

    # Write instructions for the AI, inserting the article's title and summary


    # The 'f' stands for "format". It turns this string into a template
    # so we can dynamically inject our live variables inside the curly braces {}
    prompt = f"""
      Act as an Electronic Payments Engineer [BUT NEVER SAY IT EXPLICITLY IN THE POST]. Write a LinkedIn post analyzing this news, using the EXACT same formatting, voice, and structure as my example below.

      [MY STYLE EXAMPLE - DO NOT USE THIS TOPIC]
      If you tapped your card against a POS while purchasing something, what exactly happens?
      Well, if it is an "On-Us" transaction, the authorization will be much simpler and direct.
      In simple terms (Card belonging to Bank X ➡️ POS belonging to Bank X).
      _______________________
      1- The POS forwards the transaction...
      2- The acquirer banking switch identifies...
      [END STYLE EXAMPLE]

      [NEW ARTICLE TO WRITE ABOUT]
      Title: {article['Title']}
      Context: {article['Summary']}

      RULES:
      - Start with an educational question hook.
      - Use the exact same spacing, tone, and the "➡️" arrows.
      - Use the "_______________________" divider followed by a numbered technical flow (1-5).
      - End with a "So, in a nutshell..." summary.
      - Add 5 hashtags (e.g., #Epayment #Fintech).
      - Do NOT include a name or sign-off at the end.
      """

    # Ask the AI model to read our prompt and generate the post
    response = model.generate_content(prompt)

    # Add the text the AI model just wrote to our final output
    final_output = final_output + response.text + "\n"

    # Add the original news link so you can read the real article if you want
    final_output = final_output + f"Source Link: {article['Link']}\n\n"

# ==========================================
# STEP 5: SHOW THE RESULT
# ==========================================

# Print the completely finished text to the screen
print(final_output)

# 1. CREATE THE IMAGE URL
# The AI generator blocks Make.com, so we use a guaranteed, high-quality POS terminal image
ai_image_url = "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=1200&auto=format&fit=crop"

# --- THE WEBHOOK BRIDGE ---
# Make sure there is no extra text or "@" symbols at the end
WEBHOOK_URL = "https://hook.eu1.make.com/yg9egdx101b6m78l79rbzkemihopj58e"

# 2. UPDATE THE PAYLOAD
# Package the text and the new image exactly how the Make.com switch expects it
payload = {
    "text": final_output,
    "image": ai_image_url
}

try:
    # Fire the POST request to the webhook
    switch_response = requests.post(WEBHOOK_URL, json=payload)
    switch_response.raise_for_status() # Check for errors
    print("\n✅ SUCCESS: Post securely delivered to Make.com via Webhook!")
except Exception as e:
    print(f"\n❌ ERROR routing the payload: {e}")